version: '3.8'

services:
  nestjs-api:
    image: dipeshgod/nestjs-api
    ports:
      - '3000:3000' # Map the NestJS app port

  nginx:
    image: nginx:latest
    ports:
      - '80:80' # Map the nginx server port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount your nginx.conf file

networks:
  default:
    name: nestjs-nginx-network
