name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t dipeshgod/nestjs-api .
      - name: Publish image to docker hub
        run: docker push dipeshgod/nestjs-api:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Pull image from docker hub
        run: docker pull dipeshgod/nestjs-api:latest
      - name: Stop and remove existing containers
        run: docker-compose down
      - name: Deploy using docker-compose
        run: docker-compose up -d
